istio:
  grafana:
    enabled: true
  tracing:
    enabled: true
  servicegraph:
    enabled: true
  ingress:
    service:
      type: LoadBalancer
  gateways:
    istio-ingressgateway:
      type: LoadBalancer
    istio-egressgateway:
      type: LoadBalancer

echo:
  host: echo.minikube
  deployments:
    - name: v1
      weight: 80
    - name: v2
      weight: 15
      canary: true
    - name: v3
      weight: 5
      canary: true
      http_match:
        headers:
          - name: will-you-let-me-in
            value: always

traefik:
  enabled: true
  kubernetes:
    ingressClass: traefik
  serviceType: LoadBalancer
  rbac:
    enabled: true
  dashboard:
    enabled: true
    domain: traefik.minikube
  accessLogs:
    enabled: true

nginx-ingress:
  enabled: true
  controller:
    service:
      type: LoadBalancer
