istio:
  grafana:
    enabled: true
  tracing:
    enabled: true
  servicegraph:
    enabled: true
  ingress:
    service:
      type: NodePort
  gateways:
    istio-ingressgateway:
      type: NodePort
    istio-egressgateway:
      type: NodePort

echo:
  host: echo.minikube
  deployments:
    - name: v1
      weight: 80
    - name: v2
      weight: 19
    - name: v3
      weight: 1
      http_match:
        headers:
          - name: user
            value: json

traefik:
  enabled: true
  kubernetes:
    ingressClass: traefik
  serviceType: NodePort
  rbac:
    enabled: true
  dashboard:
    enabled: true
    domain: traefik.minikube
  accessLogs:
    enabled: true
