traefik:
  enabled: true
  fullnameOverride: traefik
  serviceType: NodePort
  rbac:
    enabled: true
  dashboard:
    enabled: true
    domain: traefik.minikube
  accessLogs:
    enabled: true

echo:
  deployments:
    v1: "v1"
    v2: "v2"
    v3: "v3"

routing:
  rules:
    echo.minikube:
      - service: echo-v1
        port: 80
        path: /
        weight: 85%
      - service: echo-v2
        port: 80
        path: /
        weight: 10%
      - service: echo-v3
        port: 80
        path: /
        weight: 5%